<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>


<!doctype html>
<head>
    <meta charset="utf-8">
    <title>Site Maintenance</title>
    <meta name="Author" content="Taoufiq Ait Ali">
    <style>
        body { text-align: center; padding: 150px; }
        h1 { font-size: 50px; }
        body { font: 20px Helvetica, sans-serif; color: #333; }
        article { display: block; text-align: left; width: 650px; margin: 0 auto; }
        a { color: #dc8100; text-decoration: none; }
        a:hover { color: #333; text-decoration: none; }
    </style>
</head>



<article>
    <img src="images/logo.svg" />
    <br>
    <h1>We&rsquo;ll be back soon!</h1>
    <div>
        <p>Sorry for the inconvenience but we&rsquo;re performing some maintenance at the moment.  We&rsquo;ll be back online shortly!</p>
        <p>&mdash; The Team</p>
    </div>
</article>
